In [20]:
# Import required libraries
import pandas as pd
import numpy as np

In [21]:
# Create a sample dataset with missing values
data = {
    "Name": ["Rahul", "Priya", "Anuj"],
    "Age": [25, np.nan, 29],
    "Salary": [30000, 40000, np.nan]
    }
df = pd.DataFrame(data)
df

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya   NaN  40000.0
2   Anuj  29.0      NaN

In [ ]:
# 1. detect missing values in the dataset

print("Missing value analysis using isna():")
# Use isna() to identify missing (NaN) values in each cell
display(df.isna())

print("Total Missing values in each column:")
# Use isna().sum() to count missing values in each column 
df.isna().sum()

Boolean Values:

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True

Missing values per column:

Name      0
Age       1
Salary    1
dtype: int64

In [23]:
# 2. Replace missing Age with mean
mean_age = df["Age"].mean()
print(f"Mean Age: {mean_age}")

# Use fillna() to fill NaN values in the Age column with the calculated mean age
df["Age"] = df["Age"].fillna(mean_age)
df["Age"] = df["Age"].fillna(mean_age)

print("Dataset after filling missing age values:")
df

Mean Age: 27.0
Dataset after filling missing age values:

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya  27.0  40000.0
2   Anuj  29.0      NaN

In [ ]:
# 3. Replace missing salary values with zero 
df["Salary"] = df["Salary"].fillna(0)

print("Updated dataset after handling missing salary values:")
df

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya  27.0  40000.0
2   Anuj  29.0      0.0