In [10]:
# 1. Import Pandas library
import pandas as pd

In [11]:
# Create employee dataset using a dictionary
employees = {
    "Name": ["Rahul", "Priya", "Amit", "Anuj"],
    "Age": [25, 30, 28, 35],
    "Department": ["HR", "IT", "Finance", "IT"],
    "Salary": [30000, 50000, 45000, 60000]
}

# Convert dictionary into DataFrame
df = pd.DataFrame(employees)

# Display complete DataFrame
print("Employee details: ")
df

Employee details:

    Name  Age Department  Salary
0  Rahul   25         HR   30000
1  Priya   30         IT   50000
2   Amit   28    Finance   45000
3   Anuj   35         IT   60000

In [12]:
# 1. Display first two employee records
print("First two employee records:")
df.head(2)

First two employee records:

    Name  Age Department  Salary
0  Rahul   25         HR   30000
1  Priya   30         IT   50000

In [13]:
# 2. Generate summary statistics for numerical columns
print("Summary Statistics: ")
df.describe()

Summary Statistics:

             Age   Salary
count   4.000000      4.0
mean   29.500000  46250.0
std     4.203173  12500.0
min    25.000000  30000.0
25%    27.250000  41250.0
50%    29.000000  47500.0
75%    31.250000  52500.0
max    35.000000  60000.0

In [14]:
# 3. Filter employees belonging to IT department
it_employees = df[df["Department"] == "IT"]

print("Filtered employee records for the IT department:")
it_employees

Filtered employee records for the IT department:

    Name  Age Department  Salary
1  Priya   30         IT   50000
3   Anuj   35         IT   60000

In [15]:
# 4. Add Bonus column (10% of salary)
df["Bonus"] = df["Salary"] * 0.10

# Display updated DataFrame
print("Employee records with calculated bonus:")
df

Employee records with calculated bonus:

    Name  Age Department  Salary   Bonus
0  Rahul   25         HR   30000  3000.0
1  Priya   30         IT   50000  5000.0
2   Amit   28    Finance   45000  4500.0
3   Anuj   35         IT   60000  6000.0